services:
  # ----------------------
  # Jenkins CI Server
  # ----------------------
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
      args:
        DOCKER_GID: 999  # Replace with your host Docker group GID
    container_name: jenkins
    ports:
      - "8081:8080"       # Jenkins Web UI
      - "50000:50000"     # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to run Docker
      - .:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

  # ----------------------
  # MLflow Tracking Server
  # ----------------------
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.16.2
    container_name: mlflow-server
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow:/mlflow
    restart: always

  # ----------------------
  # Model Trainer
  # ----------------------
  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile
    container_name: diabetes-trainer
    depends_on:
      - mlflow-server
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    volumes:
      - ./model:/app/model
      - ./mlruns:/app/mlruns
    restart: "no"


  # ----------------------
  # FastAPI Prediction API
  # ----------------------
  diabetes-api:
    build:
      context: ./diabetes-api
      dockerfile: Dockerfile
    container_name: diabetes-api
    depends_on:
      - mlflow-server
      - trainer
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - MODEL_PATH=/app/model/diabetes_rf_model.pkl
    volumes:
      - ./model:/app/model
      - ./mlruns:/app/mlruns
    ports:
      - "8000:8000"
    command: ["./start-api.sh"]
    restart: always

volumes:
  jenkins_home:
