global:
  scrape_interval: 5s  # How often to scrape metrics
  evaluation_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape FastAPI diabetes prediction API
  - job_name: 'diabetes-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['diabetes-api:8000']

  # Optional: scrape MLflow metrics if exposed
  - job_name: 'mlflow-server'
    static_configs:
      - targets: ['mlflow-server:5000']
